<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__sameAsServiceAddress</name>
   <tag></tag>
   <elementGuidId>b8ee4c34-22f7-4cc7-8f8f-508ad5c8baf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sameAsServiceAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sameAsServiceAddress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Same As Service Address&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>25aca502-49a5-4b47-9785-9ce02b64ffef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sameAsServiceAddress</value>
      <webElementGuid>90f6c367-f5a5-4edd-a963-df2eaacda567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>10f0ad81-2f50-42f0-85f4-5c000beef8d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded ng-valid ng-dirty ng-touched</value>
      <webElementGuid>ea3933c5-35ba-46e2-abdf-d366de0a87a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sameAsServiceAddress&quot;)</value>
      <webElementGuid>57209b89-e14d-4268-ad73-068fbe028795</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sameAsServiceAddress']</value>
      <webElementGuid>bd82cc55-55d3-4fad-95ce-7490353fb7b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/div/input</value>
      <webElementGuid>a47906d3-8055-48b8-b171-764db0cbe3b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sameAsServiceAddress' and @type = 'checkbox']</value>
      <webElementGuid>4a7d2414-300a-445c-8167-3ffda0fd5d63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
