<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Due Date</name>
   <tag></tag>
   <elementGuidId>5a286e29-188f-4f22-abd9-5ae941afd38a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dueDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dueDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Pick Date&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f19e2935-2fb4-486f-b5b4-03050c7bfdb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3f6dbd1c-2b49-4901-b2ca-a19eead4f200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dueDate</value>
      <webElementGuid>be64f618-9629-4d32-a3fa-a7733a7e4204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dueDate</value>
      <webElementGuid>2d25425f-fb88-40fe-a033-2d009e8eb7f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>dueDate</value>
      <webElementGuid>a38df491-3a91-4c25-ad97-b674892fcbff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-datepicker-input mt-1 block w-full rounded-md border border-gray-300 focus:border-indigo-500 bg-white px-3 py-3 leading-none text-base cursor-pointer ng-pristine ng-valid ng-touched</value>
      <webElementGuid>171bae70-a7bc-4996-be59-43553e7c6b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pick Date</value>
      <webElementGuid>ebd5c85a-5bfc-45bc-8aff-6913f7cd9fac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>6d0cec44-fd08-408e-8c99-3404bfa3cda6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-calendar</name>
      <type>Main</type>
      <value>mat-datepicker-1</value>
      <webElementGuid>66415c4e-cca2-4cb5-82e7-cb005d408725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>2025-01-02T12:52:35-05:00</value>
      <webElementGuid>7b3e46bf-a231-43a1-a17c-3bf92ae083ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dueDate&quot;)</value>
      <webElementGuid>b1d0dbfc-df14-4a9e-a484-432b4276ffb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dueDate']</value>
      <webElementGuid>e6cd21cd-7a88-4bef-ac0b-9ce7e701f374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-1']/div/form/div/input</value>
      <webElementGuid>dea81b8b-3252-463a-90d5-671942f043f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/mat-expansion-panel/div/div/form/div/input</value>
      <webElementGuid>3440905a-3d1e-4666-a37f-64a599c9797a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'dueDate' and @id = 'dueDate' and @placeholder = 'Pick Date']</value>
      <webElementGuid>79276c40-8943-4a11-9b7e-da1a8f948399</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
