<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Job Start Date  Time</name>
   <tag></tag>
   <elementGuidId>2c1421bb-a42d-4c4c-a219-856ca00ccd1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jobFormStartDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jobFormStartDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Job Start Date &amp; Time&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>14093dea-83a1-4b17-a9e0-1a9ace7cb9aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jobFormStartDate</value>
      <webElementGuid>d1742f7c-0a9d-4fe7-938e-6c10c6abe59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>startDateName</value>
      <webElementGuid>b4dc2c3b-1d0e-44c5-ad42-9db629cea5bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>startDate</value>
      <webElementGuid>3614b9f2-f211-4416-b0a1-9264381b2279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-1 block w-full rounded-md border border-gray-300 focus:border-indigo-500 bg-white px-3 py-3 leading-none text-base cursor-pointer ng-pristine ng-valid ng-touched</value>
      <webElementGuid>9933142a-9a30-4d59-9838-fc8e4b2e7291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pick date and time</value>
      <webElementGuid>12d9462c-74e4-4c6c-85bb-3970c47535b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>a0cf40d5-d004-43ba-9dab-f6b93af18fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobFormStartDate&quot;)</value>
      <webElementGuid>0cdb7303-3e5c-4516-a744-d31960bf3c23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jobFormStartDate']</value>
      <webElementGuid>998bcfa7-b6ff-4443-8956-7523027f7279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-1']/div/form/div[2]/input</value>
      <webElementGuid>81186e8c-0dfb-47ab-bcbc-c3f378803f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/mat-expansion-panel/div/div/form/div[2]/input</value>
      <webElementGuid>d432dcc6-ebd2-4301-a0a9-1a68e568e040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'jobFormStartDate' and @name = 'startDateName' and @placeholder = 'Pick date and time']</value>
      <webElementGuid>d1c16565-6342-4ebb-a3bf-d1abe0f7c9f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
