<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sameAsServiceAddress</name>
   <tag></tag>
   <elementGuidId>5dcd42ce-12b7-4ab7-90d9-e3c22cb6511f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sameAsServiceAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sameAsServiceAddress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Same As Service Address&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>590a18e5-f1c8-4973-a13b-942ce6437b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sameAsServiceAddress</value>
      <webElementGuid>888578b4-1c0e-4d97-9a93-7f681e97ee1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ba6b7b57-da44-4118-bef4-f879267d8355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>01a48f9b-211e-4097-bf76-021a52ec2859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sameAsServiceAddress&quot;)</value>
      <webElementGuid>1126422f-d1dd-409b-9e10-3dfad6434907</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sameAsServiceAddress']</value>
      <webElementGuid>de902f22-47a7-4d18-bb91-c91516015786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/div/input</value>
      <webElementGuid>0ef2f814-bcb4-45ed-b309-4221354fb4fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sameAsServiceAddress' and @type = 'checkbox']</value>
      <webElementGuid>62ec4af4-29c8-40f5-bf35-f4e70955102c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
