<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search_Customer</name>
   <tag></tag>
   <elementGuidId>58d3e58f-b61b-4ed6-b0a7-3d9f01ba8f6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='existing_data_container']/div/mat-form-field//input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mat-form-field-flex.ng-tns-c86-67</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.flex > .mat-form-field > .mat-form-field-wrapper > .mat-form-field-flex >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>112c7eaa-8baf-4236-88a8-e5ad80c5659f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-form-field-flex ng-tns-c86-67</value>
      <webElementGuid>daac6808-472b-4392-8c14-b520024d6349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;existing_data_container&quot;)/div[@class=&quot;flex h-18 items-center ng-star-inserted&quot;]/mat-form-field[@class=&quot;mat-form-field data-picker-search-width pl-4 ng-tns-c86-67 mat-primary mat-form-field-type-mat-input mat-form-field-appearance-fill mat-form-field-can-float ng-pristine ng-valid ng-star-inserted ng-touched mat-form-field-should-float mat-focused&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c86-67&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c86-67&quot;]</value>
      <webElementGuid>9a84fcd8-0644-4120-8039-dd4e5f9d744c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='existing_data_container']/div/mat-form-field/div/div</value>
      <webElementGuid>fabb1ba3-e5f0-45b1-960e-47ca151d6c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Customer'])[1]/following::div[5]</value>
      <webElementGuid>9981b4c5-35bf-45e6-a963-fdd8a24a3fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Existing Customers'])[1]/following::div[5]</value>
      <webElementGuid>80c7a22b-4caf-4d64-9b7c-9d4b6e039c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filters'])[1]/preceding::div[7]</value>
      <webElementGuid>937d939c-7840-4a8c-8b6b-f4a4c0c4f11b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page 1 of 1'])[1]/preceding::div[8]</value>
      <webElementGuid>d93f1981-590d-452e-8a95-997d4dd989a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/mat-form-field/div/div</value>
      <webElementGuid>95b61f06-1023-4679-a12b-de5d15d55934</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
