<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Customer_Billing Address_same-as-service-address</name>
   <tag></tag>
   <elementGuidId>c9c48002-673f-42b4-b1fa-7d774035a929</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='same-as-service-address']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#same-as-service-address</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Same As Service Address&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a45be43-068a-4ee5-946e-e1583b9fc736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>same-as-service-address</value>
      <webElementGuid>5390a580-906c-445d-ae46-f219095025ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>85c22def-d055-4cb0-8e35-6eb4c314953d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>0dd7238b-4b1f-47c3-bcb7-2cd1f288c2c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;same-as-service-address&quot;)</value>
      <webElementGuid>d143b249-7c7e-4c62-a613-5ab0e905fe80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='same-as-service-address']</value>
      <webElementGuid>b294ef64-30d1-4d04-bce4-c653c1326300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/div/div/input</value>
      <webElementGuid>c6fafb83-7723-4b69-a17c-b76a5a5e3737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'same-as-service-address' and @type = 'checkbox']</value>
      <webElementGuid>840ab741-17ee-4622-8998-60cecb5119f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
