<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose Organization</name>
   <tag></tag>
   <elementGuidId>58cd50de-460a-491f-8bf1-c62f27bc8cc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#organization</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customer_organization']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Choose Organization&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aafdc214-16ad-4fac-9f8e-b72f20fb7a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d4de4951-2e64-4fc4-b190-f1a55dbafcb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>39e4503a-e4a6-4054-9741-84af437402df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>organization</value>
      <webElementGuid>054cb461-e838-4f22-97d0-9a15328e9e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>organization</value>
      <webElementGuid>5e5bef62-fb80-4cb4-830d-fb39616b7a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>organization</value>
      <webElementGuid>0bdb14cf-f899-441a-a85e-bd8c1abaace6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-1 block w-full rounded-md border border-gray-300 focus:border-indigo-500 bg-white shadow-sm px-3 py-3 text-base leading-none ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>a4c5025b-300d-4596-9765-876ba83f00ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Choose Organization</value>
      <webElementGuid>9f0ecf14-844d-4ee0-bdb9-586e54776539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;organization&quot;)</value>
      <webElementGuid>991558f9-e472-48a7-8af4-1193d4c6cd60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='organization']</value>
      <webElementGuid>797f3458-fab5-4a57-b4d2-5e90894d25ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div/div/input</value>
      <webElementGuid>e7f479b5-2316-4dfa-967e-2e39de37150a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'organization' and @id = 'organization' and @placeholder = 'Choose Organization']</value>
      <webElementGuid>50971be1-33da-4184-9218-9b9c1f1b3f36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
