<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__customer_email</name>
   <tag></tag>
   <elementGuidId>22438365-d241-4712-8586-58be4d3aea69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customer_email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#customer_email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;John-doe@xyz.co&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5069dfb7-1908-46e5-ab9b-eaf0d768ff5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>7dd2e648-9fe4-4bad-a555-0578e7d6deff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer_email</value>
      <webElementGuid>5610f817-c5c7-435d-9a56-a7e1fdf064ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer_email</value>
      <webElementGuid>da837a31-d006-4a63-a11a-421f0e618599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>customer_email</value>
      <webElementGuid>d72515f6-c1b7-464a-8e36-e05d49c2c41a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>John-doe@xyz.co</value>
      <webElementGuid>048a7cca-9e82-4a64-b238-65c13797bc27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-1 block w-full rounded-md border border-gray-300 focus:border-indigo-500 bg-white shadow-sm px-2.5 py-3 leading-none text-base ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>95f98c6e-8d2d-4abd-8871-36081c4459dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_email&quot;)</value>
      <webElementGuid>e6611d46-da98-4dff-96f1-d57ef8509875</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customer_email']</value>
      <webElementGuid>550fca8c-391d-4b01-8fd2-90f9acdd9e92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>7fa366c8-5212-475c-ac47-eaff72dc537d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'customer_email' and @id = 'customer_email' and @placeholder = 'John-doe@xyz.co']</value>
      <webElementGuid>b2e7ff7a-203f-4350-a3f9-32f763af28ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
