<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Users_ search area</name>
   <tag></tag>
   <elementGuidId>dadab32c-b443-475f-862b-b2391679b497</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='desktop-search-candidate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;desktop-search-candidate&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search Users...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2594c376-2983-4e01-a848-aa189141820b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>30a70359-1d66-4a6b-8b83-2b46328821d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>desktop-search-candidate</value>
      <webElementGuid>b2b0149d-5cd0-40c4-aaf3-5e26670ab60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>undefined hidden w-full rounded-md border-0 py-1.5 pl-10 text-sm leading-6 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:block</value>
      <webElementGuid>cf59ed20-99b6-4fa8-81ab-05067808f8a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Users...</value>
      <webElementGuid>8abc9755-9df3-4a88-b569-ed08ae04d12c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;grid grid-rows-[auto_1fr_auto] w-full bg-gray-100 min-h-full&quot;]/main[@class=&quot;-mt-24&quot;]/div[@class=&quot;mx-auto group w-[86rem] transition-all py-3 sm:px-6 lg:px-8&quot;]/div[@class=&quot;flex flex-1 h-full space-x-4&quot;]/section[@class=&quot;flex flex-1 min-w-0 mt-0 flex-col lg:order-last&quot;]/div[@class=&quot;mt-3 flex h-full flex-col&quot;]/div[@class=&quot;relative w-full overflow-hidden bg-white flex-1 rounded-lg shadow px-4&quot;]/div[@class=&quot;p-2 h-full&quot;]/div[@class=&quot;flow-root h-full&quot;]/div[@class=&quot;h-full  -mx-4 -my-2 overflow-x-auto overflow-y-clip sm:-mx-6 lg:-mx-8&quot;]/div[@class=&quot;h-full inline-block min-w-full align-middle sm:px-6 lg:px-8&quot;]/div[@class=&quot;min-h-full table relative p-3 min-w-full&quot;]/div[@class=&quot;undefined sticky top-0 mx-auto pb-3 border-b sm:flex sm:items-center sm:justify-between bg-white&quot;]/div[@class=&quot;mt-3 sm:ml-4 sm:mt-0&quot;]/div[@class=&quot;flex space-x-2&quot;]/div[@class=&quot;relative flex-grow focus-within:z-10 rounded-md mx-5&quot;]/div[@class=&quot;relative&quot;]/input[@class=&quot;undefined hidden w-full rounded-md border-0 py-1.5 pl-10 text-sm leading-6 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:block&quot;]</value>
      <webElementGuid>7f30c613-3904-4476-a623-25a2f859b263</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='desktop-search-candidate']</value>
      <webElementGuid>ab43f889-d718-467d-bd36-0f61c3c63d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div/section/div/div/div/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>118d41d6-4397-4bb7-b650-6c2293fd9efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>59f9a2b2-14db-4908-8d22-0c4e5f341592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'desktop-search-candidate' and @placeholder = 'Search Users...']</value>
      <webElementGuid>c9cad75e-a9ec-42db-ba8f-92f3a7e23363</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
