<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Navigate_Users</name>
   <tag></tag>
   <elementGuidId>4f731c26-fdf1-4cb2-a035-77291a3e6b06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Users' or . = 'Users')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>span >> internal:has-text=&quot;Users&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1d52d75a-7731-4a5d-8bcd-f5fe068eb6ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-indigo-50 text-indigo-600 w-full group/item inline-flex items-center py-3 px-4 text-sm font-medium rounded-lg</value>
      <webElementGuid>33d1c98c-b2e2-4652-8e6d-0c5dbc3f1fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>bd12b880-e029-46da-aa88-c28b20cae732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Users</value>
      <webElementGuid>a22aa020-4461-4de3-8334-cbc46a634bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;grid grid-rows-[auto_1fr_auto] w-full bg-gray-100 min-h-full&quot;]/main[@class=&quot;-mt-24&quot;]/div[@class=&quot;mx-auto group w-[86rem] transition-all py-3 sm:px-6 lg:px-8&quot;]/div[@class=&quot;flex flex-1 h-full space-x-4&quot;]/aside[@class=&quot;w-80 mt-3 overflow-y-auto rounded-lg shadow self-start sticky top-4&quot;]/div[@class=&quot;p-4 bg-white&quot;]/ul[@class=&quot;space-y-2 [&amp;>li]:cursor-pointer&quot;]/li[2]/span[@class=&quot;bg-indigo-50 text-indigo-600 w-full group/item inline-flex items-center py-3 px-4 text-sm font-medium rounded-lg&quot;]</value>
      <webElementGuid>b20c6099-0a84-4f86-bb81-f8abdd2c6328</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div/aside/div/ul/li[2]/span</value>
      <webElementGuid>35cb2910-9168-4582-9722-1a8bee76cdbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Details'])[1]/following::span[1]</value>
      <webElementGuid>655bfe1e-928c-4bc3-990d-052978f53a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign out'])[2]/following::span[3]</value>
      <webElementGuid>0014a180-ca1f-43c1-b9d6-a326d8999ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Module Access'])[1]/preceding::span[2]</value>
      <webElementGuid>4000c062-2248-414e-80b8-1fc202b010fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span</value>
      <webElementGuid>de2a3c9d-c4c4-42c5-8220-527406ab56cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Users' or . = 'Users')]</value>
      <webElementGuid>c03b6bcf-0d8a-4a68-8b19-85aaa7c67525</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
