<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>81562326-700b-436a-88d1-64ff04089c9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SIvCob']/a[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(5)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;தமிழ்&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4724197e-f0b9-47bc-aeea-881c6b5be573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.co.in/setprefs?sig=0_OLLAAXRJzJ8jpOk7isdIvTGrpx0%3D&amp;hl=ta&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwip5ZqeicKKAxV_TWwGHRnvAxkQ2ZgBCBw</value>
      <webElementGuid>bcc94ad9-6812-42ec-aa7b-e4ab38e75b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>தமிழ்</value>
      <webElementGuid>fb759cb9-48d1-4ce7-b862-25abf53356c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SIvCob&quot;)/a[5]</value>
      <webElementGuid>7cd17903-d4e1-43ec-b2aa-4051bc783a7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SIvCob']/a[5]</value>
      <webElementGuid>991b603a-9d3c-4258-91f1-2010d7d63131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'தமிழ்')]</value>
      <webElementGuid>aae9fda0-ce36-4ebc-b9af-59963ca0ed20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='मराठी'])[1]/following::a[1]</value>
      <webElementGuid>be2c38b4-3610-44ee-8f2f-1adc27054b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='తెలుగు'])[1]/following::a[2]</value>
      <webElementGuid>70630b5d-7e19-47d6-9b3a-fb72f99d3502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ગુજરાતી'])[1]/preceding::a[1]</value>
      <webElementGuid>4b5a559a-e5d1-4a04-9732-4beb994ebe2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ಕನ್ನಡ'])[1]/preceding::a[2]</value>
      <webElementGuid>09b4c36a-706a-4515-becb-b927a2480c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='தமிழ்']/parent::*</value>
      <webElementGuid>06045beb-256e-440d-9be5-2586f88f6e85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.co.in/setprefs?sig=0_OLLAAXRJzJ8jpOk7isdIvTGrpx0%3D&amp;hl=ta&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwip5ZqeicKKAxV_TWwGHRnvAxkQ2ZgBCBw')]</value>
      <webElementGuid>59060238-6cac-468d-8cf1-4450983c91ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]</value>
      <webElementGuid>430256c3-053f-4bb5-9d7e-8aceb4a2c37d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.co.in/setprefs?sig=0_OLLAAXRJzJ8jpOk7isdIvTGrpx0%3D&amp;hl=ta&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwip5ZqeicKKAxV_TWwGHRnvAxkQ2ZgBCBw' and (text() = 'தமிழ்' or . = 'தமிழ்')]</value>
      <webElementGuid>8bc34454-3ad9-4318-b7c2-c3f80fcefcf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
