<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Parts_Minimum Qty</name>
   <tag></tag>
   <elementGuidId>f73771f8-6196-4548-872a-1fb19780db75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#minimumQty_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='minimumQty_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter Minimum Qty&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46be8589-b2c8-4452-bce9-144576283c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>f663e493-a4ee-449a-b043-b86ffb76e44e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>minimumQty</value>
      <webElementGuid>33396e14-eee5-4bf9-a813-247e36df31b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-4 block w-full rounded-md border border-gray-300 focus:border-indigo-500 bg-white shadow-sm px-3 py-3 leading-none text-base ml-2.5 ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>0089be3f-1287-45fa-9a33-926cb5237c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>minimumQty_0</value>
      <webElementGuid>c8994826-01a4-4730-9e47-91970c12db42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>minimumQty_0</value>
      <webElementGuid>ed73705b-3c0d-4e14-896d-804015b4280f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Minimum Qty</value>
      <webElementGuid>7ddd250a-d605-465c-b410-14e00bc24034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;minimumQty_0&quot;)</value>
      <webElementGuid>ea2c208f-34af-40e7-b181-cf4e8610851d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='minimumQty_0']</value>
      <webElementGuid>43758387-1b4a-43a6-896c-c364eaf9abd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-3']/div/div/form/div/div[3]/input</value>
      <webElementGuid>15e3d0ec-40e6-4e59-aba2-434b25abd65c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/form/div/div[3]/input</value>
      <webElementGuid>ed709de2-ced4-4076-80ff-67e11a0f33fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'minimumQty_0' and @id = 'minimumQty_0' and @placeholder = 'Enter Minimum Qty']</value>
      <webElementGuid>879ddb5e-ae2a-46de-bb81-26dff4a7fd2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
