<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Parts_Tax Name</name>
   <tag></tag>
   <elementGuidId>0b28b5e7-1e89-4d41-9330-77543da80763</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#taxName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='taxName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter Tax Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7bc65c21-54d1-45d4-9589-7386f618517e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5aa50399-706c-4989-88e9-ddd36a34cf88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>taxName</value>
      <webElementGuid>65df5fa8-c42c-4f76-aac9-36de79e57fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>tax_name</value>
      <webElementGuid>f94a6132-0bf9-4b23-9cac-ef04af58ecc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>taxName</value>
      <webElementGuid>cada1f6c-186e-43dc-9c66-490ddabc25e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-1 block w-full rounded-md border border-gray-300 focus:border-indigo-500 bg-white px-3 py-3 leading-none text-base ng-pristine ng-valid ng-touched</value>
      <webElementGuid>350e86e8-c587-4f7a-941c-f24f1a98ef72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Tax Name</value>
      <webElementGuid>e28e5c94-7c74-4efa-b528-3d48f9eeff56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;taxName&quot;)</value>
      <webElementGuid>b4099785-05e3-459d-bdd9-2c04fb2c585e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='taxName']</value>
      <webElementGuid>e61ee770-17f9-450f-a37a-0da7e47529e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-2']/div/form/div/div[2]/input</value>
      <webElementGuid>b9111fdf-8564-4755-bcda-cd777d4891a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/mat-expansion-panel/div/div/form/div/div[2]/input</value>
      <webElementGuid>cbbb2469-7b78-439f-b121-66f1f1fce4fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'taxName' and @id = 'taxName' and @placeholder = 'Enter Tax Name']</value>
      <webElementGuid>d7410a23-7dd2-4859-ba34-6f91c839d793</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
