<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Parts_Available Qty</name>
   <tag></tag>
   <elementGuidId>5d18b81c-015f-4efc-b02b-34d6e2b36676</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#availableQty_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='availableQty_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter Available Qty&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae3188f8-a148-40b7-a67c-53f7f62e0856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4a22842f-ddae-4fc2-82e3-9c945e50a74b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>availableQty</value>
      <webElementGuid>593b1390-22b9-4aeb-a891-a4ddb26d5d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-4 block w-full rounded-md border border-gray-300 focus:border-indigo-500 bg-white shadow-sm px-3 py-3 leading-none text-base ml-1 ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>8faec0d1-ed99-4dd8-8d71-ed19343735d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>availableQty_0</value>
      <webElementGuid>801d8414-781a-441d-9abc-1692de1d452c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>availableQty_0</value>
      <webElementGuid>82fbd83f-07b3-4d1a-8b72-6e02fcd1c99c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Available Qty</value>
      <webElementGuid>ac4422d2-4842-468b-b5e2-2f3623313f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;availableQty_0&quot;)</value>
      <webElementGuid>5d35c6e3-6adf-4708-9017-3166c98f2e08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='availableQty_0']</value>
      <webElementGuid>66bcff58-aa24-4cff-a686-612d34eb4ae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-3']/div/div/form/div/div[2]/input</value>
      <webElementGuid>27735513-b978-42c0-b3da-f29d1fab5f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/form/div/div[2]/input</value>
      <webElementGuid>d7bd55db-d60d-4b96-8ee7-256ed32f0365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'availableQty_0' and @id = 'availableQty_0' and @placeholder = 'Enter Available Qty']</value>
      <webElementGuid>f6c0b72d-a116-4c51-8c95-af503af54266</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
