<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Parts_USD_sellingPrice</name>
   <tag></tag>
   <elementGuidId>136297cc-6399-45e8-a34a-71fa5f51c41b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sellingPrice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sellingPrice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter Selling Price&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3916d013-c502-4c48-868c-ce77bbde33cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4b64f3ad-bb3a-44d5-98d1-f6ec67e26044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sellingPrice</value>
      <webElementGuid>b8b0cfe5-97c6-4e33-8c62-299cfb6803a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>sellingPrice</value>
      <webElementGuid>6f0ce152-48e0-4846-ba20-552d5cfd8208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sellingPrice</value>
      <webElementGuid>02d56133-ad7f-446f-be8a-51e24cbc4f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-1 block w-full rounded-md border border-gray-300 rounded-l-none focus:border-indigo-500 bg-white px-3 py-3 leading-none text-base selling-price ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>d9ded9ad-9421-4f43-a75f-82cbc71871a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Selling Price</value>
      <webElementGuid>2df80038-7676-444b-8d33-33a7c65f20aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>b0e48c5b-cd3a-465a-94bc-ff80c94864bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sellingPrice&quot;)</value>
      <webElementGuid>09442509-7d77-4284-a736-039705134ff9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sellingPrice']</value>
      <webElementGuid>1820c112-3f64-4e8e-8bac-8df2be164e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-1']/div/form/div/div[7]/div/input</value>
      <webElementGuid>7b75dae5-cbad-44e2-a954-935dd8a878c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>a2797654-f464-4047-8117-8ca35d746ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'sellingPrice' and @id = 'sellingPrice' and @placeholder = 'Enter Selling Price']</value>
      <webElementGuid>d2a3e0c0-a837-4c27-8f9f-94fde4070833</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
