<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click-customer</name>
   <tag></tag>
   <elementGuidId>887b9e7c-4507-4a5e-a3c1-2e6d5017a039</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/div/section/div/div/div/div/div/div/div/table/tbody/tr/td[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Brothergutters-NorthJacksonville,FL Brothergutters-NorthJacksonville,FL&quot;i] >> [data-testid=&quot;flowbite-tooltip-target&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>48938f85-d860-4007-89ee-00e2160127eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-fit</value>
      <webElementGuid>c526e56e-4a86-47a8-a50b-3dd7d1c4caf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>flowbite-tooltip-target</value>
      <webElementGuid>adc6b734-84aa-4d3d-87e6-99c96fe915e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>:rk2:</value>
      <webElementGuid>5cb837a9-65e2-4654-9008-0c685f5ab534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Brothergutters-NorthJacksonville,FL</value>
      <webElementGuid>6bb4a874-c375-4a64-99be-eb157f613259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;grid grid-rows-[auto_1fr_auto] w-full bg-gray-100 min-h-full&quot;]/main[@class=&quot;-mt-24&quot;]/div[@class=&quot;mx-auto h-full  max-w-[86rem] py-3 sm:px-6 lg:px-8&quot;]/div[@class=&quot;h-full flex flex-1 space-x-4&quot;]/section[@class=&quot;flex h-full min-w-0 flex-1 flex-col lg:order-last&quot;]/div[@class=&quot;h-full&quot;]/div[@class=&quot;relative h-full w-full overflow-hidden bg-white rounded-lg shadow px-4&quot;]/div[@class=&quot;p-2 h-full&quot;]/div[@class=&quot;flow-root h-full&quot;]/div[@class=&quot;-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8 h-full&quot;]/div[@class=&quot;h-full inline-block min-w-full py-4 align-middle sm:px-6 lg:px-8&quot;]/div[@class=&quot;min-h-full table relative p-3 min-w-full&quot;]/table[@class=&quot;w-full h-full divide-y divide-gray-300&quot;]/tbody[@class=&quot;divide-y min-h-full divide-gray-200&quot;]/tr[1]/td[@class=&quot;cursor-pointer text-indigo-500 font-medium underline [&amp;>div]:w-auto [&amp;>div]:whitespace-nowrap [&amp;>div]:text-ellipsis py-4 pl-4 pr-3 text-sm sm:pl-0 [&amp;>div]:overflow-hidden&quot;]/div[@class=&quot;w-fit&quot;]</value>
      <webElementGuid>58cb862d-d048-4384-bd65-556347e2f248</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div/section/div/div/div/div/div/div/div/table/tbody/tr/td[2]/div</value>
      <webElementGuid>45e7e03e-4f52-48b1-93d7-fc1d6e4106cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Customer'])[1]/following::div[14]</value>
      <webElementGuid>920a16ea-5f70-438c-9277-cc820effc46b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brothergutters-NorthJacksonville,FL'])[2]/preceding::div[1]</value>
      <webElementGuid>32271fdc-46d6-404e-b119-cee5087b0ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='madhu.jayakumar@zuper.co'])[1]/preceding::div[4]</value>
      <webElementGuid>3ad897f2-b2e7-474a-aa53-1e20cf135a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Brothergutters-NorthJacksonville,FL']/parent::*</value>
      <webElementGuid>2a49e0fd-841c-41d1-945f-33a5c3a99ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div</value>
      <webElementGuid>74c1f66c-8365-4ee6-ae01-cc56c511a1ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Brothergutters-NorthJacksonville,FL' or . = 'Brothergutters-NorthJacksonville,FL')]</value>
      <webElementGuid>03ac2f84-a3ef-41ce-a2a0-0144a67de706</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
