<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Customersname</name>
   <tag></tag>
   <elementGuidId>4bccdbac-e178-49da-81b4-852c641445f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='desktop-search-candidate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;desktop-search-candidate&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search Customers...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>372cdf49-e943-4888-984a-b143e0796f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d2341589-9562-4497-84fc-230ea2c6d2a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>desktop-search-candidate</value>
      <webElementGuid>ebf90ba9-cb14-4a0d-81c2-8ef89c2ded68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>undefined hidden w-full rounded-md border-0 py-1.5 pl-10 text-sm leading-6 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:block</value>
      <webElementGuid>94f9cf13-02bc-4991-ba38-36cc05e96307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Customers...</value>
      <webElementGuid>73115b60-1f8b-4e59-9dfd-4ebe35e92101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;grid grid-rows-[auto_1fr_auto] w-full bg-gray-100 min-h-full&quot;]/main[@class=&quot;-mt-24&quot;]/div[@class=&quot;mx-auto h-full  max-w-[86rem] py-3 sm:px-6 lg:px-8&quot;]/div[@class=&quot;h-full flex flex-1 space-x-4&quot;]/section[@class=&quot;flex h-full min-w-0 flex-1 flex-col lg:order-last&quot;]/div[@class=&quot;h-full&quot;]/div[@class=&quot;relative h-full w-full overflow-hidden bg-white rounded-lg shadow px-4&quot;]/div[@class=&quot;p-2 h-full&quot;]/div[@class=&quot;flow-root h-full&quot;]/div[@class=&quot;-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8 h-full&quot;]/div[@class=&quot;h-full inline-block min-w-full py-4 align-middle sm:px-6 lg:px-8&quot;]/div[@class=&quot;min-h-full table relative p-3 min-w-full&quot;]/div[@class=&quot;undefined sticky top-0 mx-auto pb-3 border-b sm:flex sm:items-center sm:justify-between bg-white&quot;]/div[@class=&quot;mt-3 sm:ml-4 sm:mt-0&quot;]/div[@class=&quot;flex space-x-2&quot;]/div[@class=&quot;relative flex-grow focus-within:z-10 rounded-md mx-5&quot;]/div[@class=&quot;relative&quot;]/input[@class=&quot;undefined hidden w-full rounded-md border-0 py-1.5 pl-10 text-sm leading-6 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:block&quot;]</value>
      <webElementGuid>53b81190-19de-47fe-b270-fdeccdd76509</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='desktop-search-candidate']</value>
      <webElementGuid>ef3efdd4-1356-4de4-b7a7-509a296ecabf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div/section/div/div/div/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>ee7e1282-1da2-49bf-9cc0-8239a2c476b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b3c76ece-35da-4757-9325-b89afca9d507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'desktop-search-candidate' and @placeholder = 'Search Customers...']</value>
      <webElementGuid>bdf534b5-1e73-46d8-991a-cf5fd0ce3299</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
