<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_New PartService</name>
   <tag></tag>
   <elementGuidId>43216e1c-9605-4b0f-aea2-a74fb22e44be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.flex.flex-2.mr-4.ng-star-inserted > div.mx-2.ng-star-inserted > #undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='undefined'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; New Part/Service&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>284e03b1-ba28-44f1-b57c-104a04030ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>1618d7af-2ef5-4a5e-b12d-f7f1467b4658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-primary text-white inline-flex border border-gray-300 items-center px-4 py-3 h-9 shadow-xs text-base font-medium rounded-md text-gray-700 bg-white cursor-pointer focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 ng-star-inserted</value>
      <webElementGuid>1d6bec9b-6b94-49f5-83c6-73558586d8c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/products/new</value>
      <webElementGuid>02825720-2aa1-4454-b6fb-ab5d449997bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New Part/Service</value>
      <webElementGuid>268b1a8e-e310-4edf-aebe-a790d3cf101d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;zuper-splash-screen-hidden light theme-default ng-tns-0-5&quot;]/app-root[1]/layout[@class=&quot;ng-star-inserted&quot;]/thin-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;flex flex-col flex-auto w-full min-w-0 w-full overflow-hidden&quot;]/div[2]/breadcrumb[1]/div[@class=&quot;flex items-center bg-white border-light border-b w-full h-14 ng-star-inserted&quot;]/div[@class=&quot;flex flex-2 mr-4 ng-star-inserted&quot;]/div[@class=&quot;mx-2 ng-star-inserted&quot;]/a[@id=&quot;undefined&quot;]</value>
      <webElementGuid>4bc1b78d-4465-417c-878e-a8513724a4ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='undefined'])[2]</value>
      <webElementGuid>73622163-dab4-4951-bea3-89d0848b3a05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Groups'])[1]/following::a[1]</value>
      <webElementGuid>fe5c2d24-ef42-480e-a4e0-517e5e141ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parts &amp; Services'])[2]/following::a[2]</value>
      <webElementGuid>fc17dfb4-1647-4105-bd76-ca54b3eaf7b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/products/new')]</value>
      <webElementGuid>72fd62d8-c246-4b0e-a35c-3501dd48dd76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//breadcrumb/div/div[2]/div/a</value>
      <webElementGuid>84d6a84c-a653-467b-9f41-b5e89d17151d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'undefined' and @href = '/products/new' and (text() = 'New Part/Service' or . = 'New Part/Service')]</value>
      <webElementGuid>43d02912-cd1e-40cd-b513-eb758d0e7c7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
