<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Org_Billing Address_same-as-service-address</name>
   <tag></tag>
   <elementGuidId>c9ea4422-828a-4296-a537-29842f8ae130</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#same-as-service-address</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='same-as-service-address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Same As Service Address&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea8f014a-5a5c-4edb-a9c3-58d2f276bb65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>same-as-service-address</value>
      <webElementGuid>05299e46-9b14-4c60-9994-ac7e1788a81d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fe3d933f-ad07-4d7e-99a4-9c955ad4f440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>b6ea4f48-b7fb-47e6-92f3-63e3fc4c7e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;same-as-service-address&quot;)</value>
      <webElementGuid>93e5621c-80fe-47f2-b75c-7ceda5123976</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='same-as-service-address']</value>
      <webElementGuid>a9324a5c-c304-4d03-8c1f-f508acb2f2dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/div/div/input</value>
      <webElementGuid>c06d60ad-907c-414a-b52f-9115cc588c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'same-as-service-address' and @type = 'checkbox']</value>
      <webElementGuid>04e48a59-1088-4c85-9f63-78594ef6cac8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
