<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Organization_Email</name>
   <tag></tag>
   <elementGuidId>f10696a7-7561-479c-9d48-1ffead7c3078</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#organization-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='organization-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;John-doe@xyz.co&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae9f14bf-1231-4b75-bdc4-8f8786a71547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>bedb487a-b38e-4283-bad5-17e313a70d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>organization-email</value>
      <webElementGuid>7e37d542-41de-427e-8fd8-30092db64891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>organization-email</value>
      <webElementGuid>214ef069-0e41-46dd-875a-35ffee70e081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>organization_email</value>
      <webElementGuid>1cbc6fbd-87de-46a0-a52f-d399cb8ffb98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>John-doe@xyz.co</value>
      <webElementGuid>5701a5da-85da-4d20-b8d3-244586fe38ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-1 block w-full rounded-md border border-gray-300 focus:border-indigo-500 bg-white shadow-sm px-2.5 py-3 leading-none text-base ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>a6f0ddc8-3363-457c-9cc2-be2cd2b5127c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;organization-email&quot;)</value>
      <webElementGuid>1a525c00-353d-4599-90ca-fa935feee393</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='organization-email']</value>
      <webElementGuid>3d6256f0-677c-48fa-b6f7-a19e9bacdc7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>b8388f9f-dc53-4821-b0ca-98a73d1f0771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'organization-email' and @id = 'organization-email' and @placeholder = 'John-doe@xyz.co']</value>
      <webElementGuid>135b53a7-3e20-4591-b170-bfca3b3c4b11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
