<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Organization_Street</name>
   <tag></tag>
   <elementGuidId>421f18c7-ca93-42a6-a836-d60e45131893</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Flat / House No, Street / Locality&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e30b44e0-8302-4ae9-b84b-5202b18af4bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9abc756f-113b-42d2-a5b4-987e54ed68f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>street</value>
      <webElementGuid>bd05dbc3-08fc-42a4-8fda-3874ae0d2bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ef4e931a-4f76-4ae9-9354-3a785e9d592e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-1 block field-full-width rounded-md border border-gray-300 focus:border-indigo-500 bg-white shadow-sm px-3 py-3 leading-none text-base ng-pristine ng-invalid ng-star-inserted pac-target-input ng-touched</value>
      <webElementGuid>6e3b1114-198c-4b36-8aff-4cf40e5fbd61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Flat / House No, Street / Locality</value>
      <webElementGuid>1c4b99c5-7a9c-4c01-a656-4d51442168aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;zuper-splash-screen-hidden light theme-default ng-tns-0-5&quot;]/app-root[1]/layout[@class=&quot;ng-star-inserted&quot;]/thin-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;flex flex-col flex-auto w-full min-w-0 w-full overflow-hidden&quot;]/div[@class=&quot;flex flex-col flex-auto&quot;]/app-new-organization[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;parent-container flex w-full&quot;]/div[@class=&quot;left-pane w-full p-4 zuper-scrollbar&quot;]/div[@class=&quot;form-container&quot;]/form[@class=&quot;primary-font ng-pristine ng-invalid ng-touched&quot;]/div[@class=&quot;mt-4 grid grid-cols-6 gap-4&quot;]/div[@class=&quot;col-span-3&quot;]/a[@class=&quot;block w-full bg-white border border-gray-200 rounded-lg col-span-3&quot;]/div[@class=&quot;px-4 pb-4 pt-2 flex flex-col&quot;]/contact-info[1]/div[@class=&quot;w-full ng-star-inserted&quot;]/form[@class=&quot;flex w-full flex-wrap contact-info-form-div ng-pristine ng-invalid ng-touched&quot;]/div[@class=&quot;px-2 field-container-full-width py-3 ng-star-inserted&quot;]/input[@class=&quot;mt-1 block field-full-width rounded-md border border-gray-300 focus:border-indigo-500 bg-white shadow-sm px-3 py-3 leading-none text-base ng-pristine ng-invalid ng-star-inserted pac-target-input ng-touched&quot;]</value>
      <webElementGuid>098f14a4-df4d-4dd2-88ac-5a06c580fc21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[6]</value>
      <webElementGuid>af29261f-f75d-45d3-9254-2470c2c17cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>da63ba99-2fe3-4596-84dd-1a3329f318d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Flat / House No, Street / Locality']</value>
      <webElementGuid>61bfc550-b83c-4879-ad24-9ca402923114</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
