<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>organization_name</name>
   <tag></tag>
   <elementGuidId>a5de7aff-7cd2-4f49-97d0-88d9f80d16f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#organization_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='organization_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Organization Name*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>262b6be7-fc8a-4519-ac5c-d155fca25ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1f11f7bb-c59a-415b-bd90-cb91c1c0f3ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>organization_name</value>
      <webElementGuid>ca3e015a-48c0-42eb-b3af-be64fb37a3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>organization_name</value>
      <webElementGuid>94e85a51-b44a-42b3-9ea4-7fafb0af8342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>organization_name</value>
      <webElementGuid>7d8f5d8b-ec71-4253-93ba-05318704166d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Eg: North Tower</value>
      <webElementGuid>33b7fcaa-0dd5-476f-841d-3ce1268aced0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-1 block w-full rounded-md border border-gray-300 focus:border-indigo-500 bg-white shadow-sm px-3 py-3 leading-none text-base ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>48f55e33-9f64-46f9-b8ac-e835ec7bb87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;organization_name&quot;)</value>
      <webElementGuid>a0ac9777-b4a2-42f6-b25b-466c8d5a44ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='organization_name']</value>
      <webElementGuid>a26e9c54-3e46-4ecc-b3e8-f6966af87fba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div/input</value>
      <webElementGuid>9b69a6bc-5d46-48c9-91eb-c4bb6ad0d077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'organization_name' and @id = 'organization_name' and @placeholder = 'Eg: North Tower']</value>
      <webElementGuid>e2446731-9592-4def-b851-05fdfe92110b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
