<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_VolvoSaabOpelAudi</name>
   <tag></tag>
   <elementGuidId>3fc1d7dc-ba79-4994-9be4-5062d4639382</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cars</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cars']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cars</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e7032c0d-101a-4e23-a61c-b873af3f6210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cars</value>
      <webElementGuid>8184aedb-efad-415c-83d0-d42a4ae0c154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cars</value>
      <webElementGuid>109f0723-82e5-46e9-9f84-f7cc8bf12c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VolvoSaabOpelAudi</value>
      <webElementGuid>3a73fcba-6c44-4b89-b130-64b7a9702be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cars&quot;)</value>
      <webElementGuid>d7a74905-227a-465d-a90e-343875510fcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cars']</value>
      <webElementGuid>15416f87-10b1-4ca8-86a4-3e44ec9b089d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='selectMenuContainer']/div[8]/div/select</value>
      <webElementGuid>3f6cc16d-f601-4273-9616-a92b338c8c6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard multi select'])[1]/following::select[1]</value>
      <webElementGuid>e8e97b59-cdfb-47d3-a619-8a6c85086be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Green'])[2]/following::select[1]</value>
      <webElementGuid>8288950e-4925-46ff-8f27-97aa4594d3ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2013-2020 TOOLSQA.COM | ALL RIGHTS RESERVED.'])[1]/preceding::select[1]</value>
      <webElementGuid>7c5aef17-f8eb-438b-86a2-130dd790c83b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/select</value>
      <webElementGuid>5eaf9c7b-2fa1-449d-8a7f-14dba72d8953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'cars' and @id = 'cars' and (text() = 'VolvoSaabOpelAudi' or . = 'VolvoSaabOpelAudi')]</value>
      <webElementGuid>93133f5f-f3b9-4d37-ac78-43e791e3d198</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
