<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Droppable</name>
   <tag></tag>
   <elementGuidId>2161d7dc-2c6d-4178-83db-9c955ca4af51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>aside.widget > ul > li:nth-of-type(2) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebar']/aside/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Droppable&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8d993974-d835-4276-8d00-8444c9eb3eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://jqueryui.com/droppable/</value>
      <webElementGuid>39373a6d-3bcf-40a2-9075-9c2ba9d8c3d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Droppable</value>
      <webElementGuid>86b7d637-3974-4b45-996c-9153afe80fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar&quot;)/aside[@class=&quot;widget&quot;]/ul[1]/li[2]/a[1]</value>
      <webElementGuid>acd9aeda-2285-42ea-9e5d-b701a2538de5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar']/aside/ul/li[2]/a</value>
      <webElementGuid>1d995761-243c-4991-8ca7-a8f8ad30ca57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Droppable')]</value>
      <webElementGuid>3dd40960-bfb0-452d-944b-d4f0f46caed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draggable'])[1]/following::a[1]</value>
      <webElementGuid>01ffcb7e-7bd6-4d6f-9f20-57079c6f0eb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interactions'])[1]/following::a[2]</value>
      <webElementGuid>7c48edc3-3b28-4a30-ad7c-a617f579eb1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resizable'])[1]/preceding::a[1]</value>
      <webElementGuid>4607e8d7-3ed2-4d2f-aaf1-deab07485609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selectable'])[1]/preceding::a[2]</value>
      <webElementGuid>eb80b830-14df-48cc-9240-05515b7fd55d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://jqueryui.com/droppable/')]</value>
      <webElementGuid>c5e8828d-09e1-4f8d-9ffb-9bd33aee8631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/ul/li[2]/a</value>
      <webElementGuid>ed25b967-80c7-46a8-b16c-5914eb2fc0ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://jqueryui.com/droppable/' and (text() = 'Droppable' or . = 'Droppable')]</value>
      <webElementGuid>15ab7154-d30c-41dd-be2a-9075146cabae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
