<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_English</name>
   <tag></tag>
   <elementGuidId>4a5fa641-1439-463e-a86c-75c64d33109c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SIvCob']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SIvCob > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;English&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7295d6f6-b0a8-4a88-8c13-6ae4389d4dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.co.in/setprefs?sig=0_OLLAAXRJzJ8jpOk7isdIvTGrpx0%3D&amp;hl=en&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjWtNKficKKAxXRS2cHHQfDM7kQ2ZgBCBY</value>
      <webElementGuid>be425988-b4d6-4f87-8eda-f938ecbc4769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>English</value>
      <webElementGuid>8152f336-af50-483c-b9a6-153ca5218a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SIvCob&quot;)/a[1]</value>
      <webElementGuid>d229f579-3ff5-40fc-9a16-81e60d216507</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SIvCob']/a</value>
      <webElementGuid>e8e98d0c-635e-4482-98dd-bf484e661082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'English')]</value>
      <webElementGuid>afde7744-77a1-4cf6-882f-ca9c4555b756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='பொருத்தமற்ற கணிப்புகளைப் புகாரளி'])[1]/following::a[1]</value>
      <webElementGuid>7ad089fb-b4c3-4d8e-8d03-7594d9c73798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='हिन्दी'])[1]/preceding::a[1]</value>
      <webElementGuid>52d26836-f75c-4ff1-81ea-cbfa9c4079c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='বাংলা'])[1]/preceding::a[2]</value>
      <webElementGuid>6acce295-8183-4e69-be6c-dbfbdb618267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='English']/parent::*</value>
      <webElementGuid>95f312d9-7421-4a40-a641-82b501ab3496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.co.in/setprefs?sig=0_OLLAAXRJzJ8jpOk7isdIvTGrpx0%3D&amp;hl=en&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjWtNKficKKAxXRS2cHHQfDM7kQ2ZgBCBY')]</value>
      <webElementGuid>5fd8fef7-aafc-49c4-837d-6d52e9f1d2f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>620c40c8-f1f7-4ba3-b11f-4faee0fddd90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.co.in/setprefs?sig=0_OLLAAXRJzJ8jpOk7isdIvTGrpx0%3D&amp;hl=en&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjWtNKficKKAxXRS2cHHQfDM7kQ2ZgBCBY' and (text() = 'English' or . = 'English')]</value>
      <webElementGuid>a17fcb33-a547-4e1a-bbb8-b45d13f4bb6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
