<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Report inappropriate predictions_btnK</name>
   <tag></tag>
   <elementGuidId>9efaf2d6-ed6b-4a03-ad22-2c2209ce8032</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='btnK'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.FPdoLc.lJ9FBc > center > input[name=&quot;btnK&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Google Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f246b725-30bf-4c8f-bc36-d65cf36c1965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gNO89b</value>
      <webElementGuid>61848cf9-d53d-4de4-a260-f6c479929666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Google Search</value>
      <webElementGuid>415c985d-2a2f-4e81-bf8f-52fc92749a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Google Search</value>
      <webElementGuid>a378e14f-49a6-4ed9-afb0-6cbb43db3c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnK</value>
      <webElementGuid>e5f22549-9ed0-4c08-9fd1-302abdec5db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eca494c2-4897-46de-b4d1-506928b6ca7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>abdf719c-a117-42b1-8911-a8264b9aaa8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>81d087ce-1ad5-41b7-a8b6-955ca6e0b9fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ved</name>
      <type>Main</type>
      <value>0ahUKEwiSl76gicKKAxWxTWwGHX0SKIUQ4dUDCBM</value>
      <webElementGuid>48052609-c104-4a1b-8593-514798ec2706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;L3eUgb&quot;]/div[@class=&quot;o3j99 ikrT4e om7nvf&quot;]/form[1]/div[1]/div[@class=&quot;A8SBwf&quot;]/div[@class=&quot;FPdoLc lJ9FBc&quot;]/center[1]/input[@class=&quot;gNO89b&quot;]</value>
      <webElementGuid>c370ef64-93b0-4768-b8bb-19f8c84624ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='btnK'])[2]</value>
      <webElementGuid>f3ceaeae-c77f-4c81-9e16-d12eecb2be14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/center/input</value>
      <webElementGuid>6f3d9f94-9eb0-4d84-abcf-ebed0640e129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'btnK' and @type = 'submit']</value>
      <webElementGuid>274ae1ff-ab6b-40ab-ae0a-587e5ee02fe2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
