<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Property Name</name>
   <tag></tag>
   <elementGuidId>e2bca6c3-ece7-4e72-8077-c9457b622ecc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#property-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='property-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Eg: North Tower&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ebf2a002-16d3-47ad-a7a7-b9330b664ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6390de4f-7a81-42e9-8fb9-9f7ce94316ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ceec8b08-faf6-4c0f-94a8-78c1e89bccea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>property-name</value>
      <webElementGuid>b0c512b7-bf53-4cb4-b64c-38054265215e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>propertyName</value>
      <webElementGuid>596e0f57-bcbd-4cb0-81b7-baceafe944c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>property-name</value>
      <webElementGuid>a788bf5e-26be-4ecb-8f9f-d16f329e2c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Eg: North Tower</value>
      <webElementGuid>070fc13c-ef61-4753-b208-418735025f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-1 block w-full rounded-md border border-gray-300 focus:border-indigo-500 bg-white shadow-sm px-3 py-3 text-base leading-none ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>c57f5e4b-1c97-4a88-b6ff-76b4a7982821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;property-name&quot;)</value>
      <webElementGuid>e3e96754-62c2-4c02-a653-f735a121a32a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='property-name']</value>
      <webElementGuid>0888c984-0ca1-4908-82fb-e65ae65119ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>0afee239-ef31-4046-ba32-01f795132498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'property-name' and @id = 'property-name' and @placeholder = 'Eg: North Tower']</value>
      <webElementGuid>bf37f242-40fb-4a9d-9808-670fafcf8aee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
