<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose Parent Property</name>
   <tag></tag>
   <elementGuidId>c976114c-ee8e-47f5-b3e1-c7223fac5578</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#parent_property</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='parent_property']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Choose Parent Property&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a4eba4a-fbb4-4798-a81c-a3e7022cc447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1ffb0074-ca7a-4c73-85aa-2bc35541dd31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3e8a2b6e-533f-4581-a89c-5ae5e610b420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>parent_property</value>
      <webElementGuid>ba51a198-86aa-41c4-93f2-d2aa8871f24b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>parent_property</value>
      <webElementGuid>b7366773-58c1-4d00-92df-d88132f96800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>parent_property</value>
      <webElementGuid>cdf16512-a73b-4040-a352-3e769e328fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-1 block w-full rounded-md border border-gray-300 focus:border-indigo-500 bg-white shadow-sm px-3 py-3 text-base leading-none ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>9072a5ef-d828-44f2-baee-f87e1da01e12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Choose Parent Property</value>
      <webElementGuid>1bf88596-0c29-45b9-816b-18c0275edc93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;parent_property&quot;)</value>
      <webElementGuid>70661335-f599-495a-9185-3eda056ee268</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='parent_property']</value>
      <webElementGuid>0f03e429-d240-4eb9-a2cc-9c2e215c096f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>d885a9d4-237c-477c-8e30-d46aaaedfb34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'parent_property' and @id = 'parent_property' and @placeholder = 'Choose Parent Property']</value>
      <webElementGuid>4dec889f-879f-43c5-8652-8e760a26610d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
