<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Property_Landmark</name>
   <tag></tag>
   <elementGuidId>b3683467-185a-4b49-90e7-15549788321c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Landmark&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a72f5580-e7f0-47be-8d63-73911ace06ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b220e2ae-8a20-487e-9752-ba293c4af523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>landmark</value>
      <webElementGuid>a1e3c3ef-7fda-4ffc-b983-bf5c827dab1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>80621f93-0188-42b0-b6df-a7742988f7f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-1 block field-full-width rounded-md border border-gray-300 focus:border-indigo-500 bg-white shadow-sm px-3 py-3 leading-none text-base ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>16815386-3b96-4f43-847f-ff87846bde36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Landmark</value>
      <webElementGuid>b31ec61e-9e61-4367-9cf1-ca5a23f7dd2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;zuper-splash-screen-hidden light theme-default ng-tns-0-5&quot;]/app-root[1]/layout[@class=&quot;ng-star-inserted&quot;]/thin-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;flex flex-col flex-auto w-full min-w-0 w-full overflow-hidden&quot;]/div[@class=&quot;flex flex-col flex-auto&quot;]/property-form[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;parent-container flex w-full&quot;]/div[@class=&quot;left-pane w-full p-4 zuper-scrollbar&quot;]/div[@class=&quot;form-container&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;mt-4 grid grid-cols-6 gap-4&quot;]/div[@class=&quot;col-span-6&quot;]/a[@class=&quot;block w-full bg-white border border-gray-200 rounded-lg col-span-3&quot;]/div[@class=&quot;px-4 pb-4 pt-2 flex flex-col&quot;]/contact-info[@class=&quot;property-address&quot;]/div[@class=&quot;w-full ng-star-inserted&quot;]/form[@class=&quot;flex w-full flex-wrap contact-info-form-div ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;px-2 py-3 field-container-half-width ng-star-inserted&quot;]/input[@class=&quot;mt-1 block field-full-width rounded-md border border-gray-300 focus:border-indigo-500 bg-white shadow-sm px-3 py-3 leading-none text-base ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>7cbc3b1f-cb6f-49f8-b0d6-874eb2aad751</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[6]</value>
      <webElementGuid>05326186-1aa2-4ce1-8562-745e9e8df5c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/input</value>
      <webElementGuid>8355b22f-3cdf-401e-8fe3-45c6d2a9f606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Landmark']</value>
      <webElementGuid>d053fe96-51f3-4a49-98e9-5cca8583cac2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
