<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Property_Zipcode</name>
   <tag></tag>
   <elementGuidId>78b01e63-7a38-46ee-8de4-e8d1404fb15a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[10]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Zipcode&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5f4a645-9249-46ab-aa18-238b31109153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>36c2bce4-f7d9-4861-9854-e726f896a9be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>zipcode</value>
      <webElementGuid>e6f195bb-192d-4880-9852-c6581bc91436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>c1627f4c-23ae-4cbf-9c22-c9d44a3b09eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-1 block field-full-width rounded-md border border-gray-300 focus:border-indigo-500 bg-white shadow-sm px-3 py-3 leading-none text-base ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>79594d84-ec99-455a-950c-a2e0752f2f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Zipcode</value>
      <webElementGuid>d573f778-2a19-42a0-92a2-e63f00dbef11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;zuper-splash-screen-hidden light theme-default ng-tns-0-5&quot;]/app-root[1]/layout[@class=&quot;ng-star-inserted&quot;]/thin-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;flex flex-col flex-auto w-full min-w-0 w-full overflow-hidden&quot;]/div[@class=&quot;flex flex-col flex-auto&quot;]/property-form[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;parent-container flex w-full&quot;]/div[@class=&quot;left-pane w-full p-4 zuper-scrollbar&quot;]/div[@class=&quot;form-container&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;mt-4 grid grid-cols-6 gap-4&quot;]/div[@class=&quot;col-span-6&quot;]/a[@class=&quot;block w-full bg-white border border-gray-200 rounded-lg col-span-3&quot;]/div[@class=&quot;px-4 pb-4 pt-2 flex flex-col&quot;]/contact-info[@class=&quot;property-address&quot;]/div[@class=&quot;w-full ng-star-inserted&quot;]/form[@class=&quot;flex w-full flex-wrap contact-info-form-div ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;px-2 py-3 field-container-half-width ng-star-inserted&quot;]/input[@class=&quot;mt-1 block field-full-width rounded-md border border-gray-300 focus:border-indigo-500 bg-white shadow-sm px-3 py-3 leading-none text-base ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>783e070d-6890-4407-9d4f-ce8fe6961775</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[10]</value>
      <webElementGuid>565d0542-1731-4aac-aa4e-f239722d34df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>9e123289-0ed8-42a8-b268-ed4017bfcaa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Zipcode']</value>
      <webElementGuid>cd6a1a87-de15-45a3-b4c8-0c1f595c169a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
