<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>4 hours</name>
   <tag></tag>
   <elementGuidId>d4a7de00-eb0d-4bbf-bd4a-c015b5a84f9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='280']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#280</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;4 hours&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>7c4e8b5d-93a6-4a9b-805b-1f39a0d29c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>280</value>
      <webElementGuid>64c002ea-2244-4265-a1b0-f302e26fd2ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> flex flex-nowrap mt-1 items-center gap-x-4 cursor-pointer px-2 py-1 rounded bg-blue-600 bg-opacity-20 </value>
      <webElementGuid>96d4cc78-ffe0-4f04-97cc-c4e4d97fd30c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>3bee6e0a-d45c-45e6-8a43-d0dd02fc816b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>103d3e89-31e4-4a8e-be65-4bfef41d1599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4 hours</value>
      <webElementGuid>bf953084-ec99-46d6-9971-db42cdb0c0a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;280&quot;)</value>
      <webElementGuid>397dc2c2-eb38-42e8-abd5-19abb03bdb0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='280']</value>
      <webElementGuid>ba6c913e-dedb-4d07-9c36-a61dc36d6b6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':rba:']/div/div[2]/div/div/fieldset/div[4]/div/ul/li</value>
      <webElementGuid>62eb9c29-a6e3-4643-8bb8-6c29cc3fc624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Session Duration'])[1]/following::li[1]</value>
      <webElementGuid>42c061fb-cda8-4beb-85ed-fe7cc135dbf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login as Zuper Admin'])[1]/following::li[1]</value>
      <webElementGuid>1d1524fc-d1ca-401d-8db3-cd7a7a116f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose User Agent'])[1]/preceding::li[3]</value>
      <webElementGuid>a844d805-df75-443a-b849-d44512fd7d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Login Reason'])[1]/preceding::li[6]</value>
      <webElementGuid>6555291e-cd86-48e7-9af6-6a30fb411ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/ul/li</value>
      <webElementGuid>3cb3250a-ea79-417c-9c45-0920a1d9a212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '280' and (text() = '4 hours' or . = '4 hours')]</value>
      <webElementGuid>2354d1ce-0eba-4b87-acb2-be59cf3250e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
