<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Hours_button</name>
   <tag></tag>
   <elementGuidId>f611209f-3dfc-4b6c-be28-b892a7bd177c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'extended-validity']//following::label[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>label >> internal:has-text=&quot;More&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ffcef88d-5f36-4258-93c9-5b0e2ea91113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>extended-validity</value>
      <webElementGuid>2af0cf9d-49e6-491b-98cf-0580da61e7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block cursor-pointer shadow-md rounded-lg border border-gray-100 bg-white p-4 text-md font-medium  hover:border-gray-200 peer-checked:border-gray-700 peer-checked:ring-1 peer-checked:ring-gray-500</value>
      <webElementGuid>4327565d-ad65-4dc0-a93b-00578c6a47c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>More</value>
      <webElementGuid>4e4e283d-a7ad-4f2d-9e00-946f7beb101b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:rba:&quot;)/div[@class=&quot;relative rounded-lg bg-white shadow dark:bg-gray-700 flex flex-col max-h-[90vh]&quot;]/div[@class=&quot;p-6 flex-1 overflow-auto pt-0&quot;]/div[@class=&quot;text-center&quot;]/div[@class=&quot;relative  py-3 flex flex-col text-left justify-items-start&quot;]/fieldset[@class=&quot;grid grid-cols-4 gap-x-4 w-full mb-2&quot;]/div[4]/label[@class=&quot;block cursor-pointer shadow-md rounded-lg border border-gray-100 bg-white p-4 text-md font-medium  hover:border-gray-200 peer-checked:border-gray-700 peer-checked:ring-1 peer-checked:ring-gray-500&quot;]</value>
      <webElementGuid>cf718c27-5df6-469f-8f13-2053be4966cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':rba:']/div/div[2]/div/div/fieldset/div[4]/label</value>
      <webElementGuid>762db3c3-e713-453a-901e-be882014d0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Session Duration'])[1]/following::label[4]</value>
      <webElementGuid>1a640ff1-4391-494d-9bc8-5ba67568ca07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login as Zuper Admin'])[1]/following::label[4]</value>
      <webElementGuid>6229a967-6790-411e-8a20-0d36e15c3a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose User Agent'])[1]/preceding::label[1]</value>
      <webElementGuid>f8eaaf73-e686-4357-b02b-889f13b1a082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Login Reason'])[1]/preceding::label[2]</value>
      <webElementGuid>5eecebb4-e2b7-4f67-955c-1ae23f1a8754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/label</value>
      <webElementGuid>058338ea-acee-4d6c-bcfb-9804332dc7d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'More' or . = 'More')]</value>
      <webElementGuid>19ff9746-75f2-4671-985e-d3e14cf8fdef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
