<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login Reason</name>
   <tag></tag>
   <elementGuidId>039ef86b-f368-4c7d-b41d-5a02c58d8fc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id=''])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;reason&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;reason&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>14ca57ed-5287-4049-aa2a-71872c62aeb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full border disabled:cursor-not-allowed disabled:opacity-50 bg-gray-50 border-gray-300 text-gray-900 focus:border-cyan-500 focus:ring-cyan-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-cyan-500 dark:focus:ring-cyan-500 p-2.5 text-sm pr-10 rounded-lg</value>
      <webElementGuid>7b5c46ff-d945-4cd0-bb4d-93216d050405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reason</value>
      <webElementGuid>7f33fd56-f0b1-44e5-aa5f-83ca45588d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>--Select--</value>
      <webElementGuid>86bd848c-7b38-43f0-816f-2ee13bf0bb98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3d0288cd-401b-4985-9434-0adcc723a9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:rba:&quot;)/div[@class=&quot;relative rounded-lg bg-white shadow dark:bg-gray-700 flex flex-col max-h-[90vh]&quot;]/div[@class=&quot;p-6 flex-1 overflow-auto pt-0&quot;]/div[@class=&quot;text-center&quot;]/div[@class=&quot;relative  py-3 flex flex-col text-left justify-items-start&quot;]/div[@class=&quot;mb-2 relative inline-block text-primary&quot;]/div[@id=&quot;trigger&quot;]/div[@class=&quot;flex [&amp;_input]:cursor-pointer [&amp;_input]:text-gray-600 [&amp;_input]:!bg-transparent&quot;]/div[@class=&quot;relative w-full&quot;]/input[@class=&quot;block w-full border disabled:cursor-not-allowed disabled:opacity-50 bg-gray-50 border-gray-300 text-gray-900 focus:border-cyan-500 focus:ring-cyan-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-cyan-500 dark:focus:ring-cyan-500 p-2.5 text-sm pr-10 rounded-lg&quot;]</value>
      <webElementGuid>d27f2a8b-cf60-45f8-b84f-8f70029f1075</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id=''])[3]</value>
      <webElementGuid>d1340468-9d63-4f35-a42e-a6f926769e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='trigger']/div/div/input)[3]</value>
      <webElementGuid>2f22fde1-9204-4a01-b3a4-d57f7964ace8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>480e4378-1b61-491b-941c-6c735e972149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'reason' and @placeholder = '--Select--' and @type = 'text']</value>
      <webElementGuid>c399a461-7ab0-4257-8765-e02bc9aaa34e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
