<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Web_selecter</name>
   <tag></tag>
   <elementGuidId>317ccab0-b438-4681-81ae-ff6fdc5926b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id=''])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;client&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;client&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92019cf9-dc11-44d1-b26f-0e8217108ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full border disabled:cursor-not-allowed disabled:opacity-50 bg-gray-50 border-gray-300 text-gray-900 focus:border-cyan-500 focus:ring-cyan-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-cyan-500 dark:focus:ring-cyan-500 p-2.5 text-sm pr-10 rounded-lg</value>
      <webElementGuid>6207a645-1e3f-46c5-87a7-90d533f88689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>client</value>
      <webElementGuid>5362bccd-c146-42c7-9fdf-3b5a1bab589b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>--Select--</value>
      <webElementGuid>7bb0ee6a-ada0-4c2e-9715-4fadf5199b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e313b9fa-4620-4464-8676-91f0f8f307c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Web V2</value>
      <webElementGuid>22e5a3d4-edeb-41d4-9c1d-7611a2e28405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:rba:&quot;)/div[@class=&quot;relative rounded-lg bg-white shadow dark:bg-gray-700 flex flex-col max-h-[90vh]&quot;]/div[@class=&quot;p-6 flex-1 overflow-auto pt-0&quot;]/div[@class=&quot;text-center&quot;]/div[@class=&quot;relative  py-3 flex flex-col text-left justify-items-start&quot;]/div[@class=&quot;mb-2 relative inline-block text-primary&quot;]/div[@id=&quot;trigger&quot;]/div[@class=&quot;flex [&amp;_input]:cursor-pointer [&amp;_input]:text-gray-600 [&amp;_input]:!bg-transparent&quot;]/div[@class=&quot;relative w-full&quot;]/input[@class=&quot;block w-full border disabled:cursor-not-allowed disabled:opacity-50 bg-gray-50 border-gray-300 text-gray-900 focus:border-cyan-500 focus:ring-cyan-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-cyan-500 dark:focus:ring-cyan-500 p-2.5 text-sm pr-10 rounded-lg&quot;]</value>
      <webElementGuid>14e3eafa-2565-4375-b693-81f7e628f3d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id=''])[2]</value>
      <webElementGuid>1399b885-41b0-4d9a-a672-8acac8069c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='trigger']/div/div/input)[2]</value>
      <webElementGuid>4c5b570a-d40a-42a6-9088-ed714a076ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>04166e1b-9020-404f-94e1-7483ed8677d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'client' and @placeholder = '--Select--' and @type = 'text']</value>
      <webElementGuid>e5e17329-e5cc-4507-a909-7b2826b317e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
